### ISSUE TITLE
Error when computing c4_part1

### ISSUE THREAD

**Issue by jtlz2** [rahmatnazali/pimage#2]
Hi - I am trying to run the code over the horse_fake.png example, but I have reduced the blocksize to decrease the runtime, with the following problem on macOS:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    forgery_detect.detect('../test_images/', image_file, '../output_images/', blockSize=8) # was 32
  File "/Users/j/src/Image-Forgery-Detection/forgery_detect/forgery_detect.py", line 22, in detect
    imageResultPath = singleImage.run()
  File "/Users/j/src/Image-Forgery-Detection/forgery_detect/image_object.py", line 82, in run
    self.compute()
  File "/Users/j/src/Image-Forgery-Detection/forgery_detect/image_object.py", line 127, in compute
    self.featuresContainer.addBlock(imageBlock.computeBlock())
  File "/Users/j/src/Image-Forgery-Detection/forgery_detect/Blocks.py", line 38, in computeBlock
    blockDataList.append(self.computeCharaFeatures(4))
  File "/Users/j/src/Image-Forgery-Detection/forgery_detect/Blocks.py", line 118, in computeCharaFeatures
    c4_part1 += self.imageGrayscalePixels[xCoordinate, yCoordinate]
TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

Any ideas?

Thanks!

**Comment by rnazali** [comment]
Hi!

As the error message shows "unsupported operand type(s) for +=: 'int' and 'tuple'", I believe the code are just trying to sum a tuple instead of int.

This can be a bug on my code. eg: fail to handle certain type of image.

Since I was no longer have the code on my laps, could you run the code again by adding a line for debugging purpose, so that your code looks like this:

on File "/Users/j/src/Image-Forgery-Detection/forgery_detect/Blocks.py", line 118
```
print self.imageGrayscalePixels[xCoordinate, yCoordinate]
c4_part1 += self.imageGrayscalePixels[xCoordinate, yCoordinate]
```

(just add print statement before line 118 to know what is actually summed.
Let me know what the console prints.

Cheers.

**Comment by vaishnavidasharadhi** [comment]
Can you tell me how did u solve that error.
Im also getting the same error

**Comment by rahmatnazali** [comment]
Will close this issue since @jtlz2  is not responding.

**Comment by rnazali** [comment]
Will close this issue since @jtlz2 is not responding.
