### ISSUE TITLE
quadratic speed up

### ISSUE THREAD

**Issue by o7n** [rahmatnazali/pimage#5]
So the loop in ImageObject.analyze

```
        for i in tqdm(range(featureContainerLength)):
            for j in range(i + 1, featureContainerLength):
```
can be changed to
```
        for i in tqdm(range(featureContainerLength-1)):
            j = i+1
```

giving a speedup of a factor >1000 on the analyze step (depending on image dimensions). 
That step on the test image goes from 384 to 0.11 seconds on my PC.

This can be done because the feature list is already sorted, so you don't have to compare each block to every other block. You only need to compare it to the next block. 

The original paper clearly states this:

>  identical blocks correspond to **adjacent** pairs in the sorted list

**Comment by rnazali** [comment]
Hi, thanks for the issue and your suggestion.

I spent countless time trying to optimize the code on my college bench, and this may be the culprit.

Feel free to submit a merge request, or in the mean time I will also patch it up and credit it to you.

**Comment by blue-j** [comment]
@o7n forgive me, I don't know Python that well.  I am trying to make this change, and can't do it successfully!

Here's the whole block (can't believe Github has no way to keep the formatting!!??).  Could I trouble you to let me know how it should be edited?  Thank you so much in advance for your time.  - J

```
  for i in tqdm.tqdm(range(feature_container_length)):
      for j in range(i + 1, feature_container_length):
          result = self.is_valid(i, j)
          if result[0]:
              self.add_dictionary(self.features_container.container[i][0],
                                  self.features_container.container[j][0],
                                  result[1])
              z += 1
          else:
              break
```

**Comment by likuilin** [comment]
Created pull request #15 - feel free to leave feedback~

**Comment by rnazali** [comment]
@likuilin thanks for the PR!

I have tried to run both previous code and suggested code on this Issue/PR. The result is identical so it looks good to me.

However, we know that the part where it takes most of the time are on the Computing time (i.e. computing features), and for me 
 it was not on the Analyzing time (i.e. analyzing pair of image block), at least for my computing power/PC specification, so I understand that the result may greatly differ according to the PC specification we are running on.

For example, using Ryzen 9 5950x this was my time when running with original code:
```
Computing time : 216.8320083618164 second
Sorting time   : 0.7583198547363281 second
Analyzing time : 0.457594633102417 second
Image creation : 0.4176652431488037 second
Total time    : 0:03:38 second 
```

and this was the time after running the code you guys suggested (@o7n and @likuilin)
```
Computing time : 214.6352927684784 second
Sorting time   : 0.7716352939605713 second
Analyzing time : 0.42810654640197754 second
Image creation : 0.4122140407562256 second
Total time    : 0:03:36 second 
```

I don't see any major improvement on Analyzing time, at least for me specifically.

The original code already has `break` code so it should only evaluate "some" of the pair block as long as it is valid denoted by `is_valid` function, and most importantly it will not evaluate the whole array of pair blocks anyway.

Do you guys have any further suggestion?

---

Anyway, since the code did work and the result from several image are truly identical, I'll accept the PR!
Big thanks for the contribution!
